<Project Sdk="Microsoft.NET.Sdk">
  
  <Import Project="..\tModLoader.targets" />
  

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" ExcludeAssets="runtime"/>
  </ItemGroup>

    <!-- Taken from: <https://github.com/krafs/Publicizer/pull/128>.  This is
         used to fix an annoying warning because the publicizer we're using
         emits a type also included by MonoMod.Utils. -->
  <Target Name="RemoveIgnoresAccessChecksToAttributeCs" AfterTargets="PublicizeAssemblies">
    <ItemGroup>
      <FilesToRemove Include="@(Compile)" Condition="'%(Filename)' == 'IgnoresAccessChecksToAttribute'"/>
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="@(FilesToRemove)"/>
    </ItemGroup>
  </Target>

  <ItemGroup>
    <Publicize Include="tModLoader" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
    <DoNotPublicize Include="tModLoader:Terraria.Tile" /> 

    <Publicize Include="FNA" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
    <Publicize Include="ReLogic" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
  </ItemGroup>
</Project>
