using System.Collections.Generic;
using System.Linq;
using Terraria;
using Terraria.ModLoader;

namespace CalamityMod.Systems.Collections
{
    /// <summary>
    /// A <see cref="ModSystem"/> that stores all of Calamity's Patreon donator's usernames.
    /// </summary>
    public sealed class DonatorsNameList : ModSystem
    {
        public static IList<string> List { get; private set; }

        /// <summary>
        /// This list contains all the donors of the current Patreon, which is for the entire Calamity Dev Team. <br /><br />
        /// <b>There is no overlap between OriginalPatreonList and this list.</b><br /><br />
        /// Any user who donates to the new team-wide Patreon gets added to this new list and removed from the old one.
        /// </summary>
        internal static IList<string> NewPatreonList { get; private set; }

        /// <summary>
        /// This list contains all the donors of the previous Patreon, which was in Fabsol's name. <br /><br />
        /// <b>There is no overlap between NewPatreonList and this list.</b><br /><br />
        /// Any user who donates to the new team-wide Patreon gets added to the new list and removed from this one. 
        /// </summary>
        internal static IList<string> OriginalPatreonList { get; private set; }

        public override void OnModLoad()
        {
            // All donors at the $10 - Brimstone tier or higher are included in the shout-out.
            // This is updated for each release.
            NewPatreonList =
            [
                "Aerosyn",
                "Aidan Spears",
                "Amandalias",
                "Arcxus",
                "Ariallis",
                "Audrey Lynn Beemus",
                "awesomechapro",
                "Azariah",
                "azazel",
                "Ballin",
                "Barrett Turner",
                "BlueRay_256",
                "Boomdiada",
                "Borb9834",
                "botbot94",
                "Bwlstorm",
                "c0d3_404",
                "Carduelis",
                "Careless_imp",
                "Chin",
                "Cinder",
                "CrazyGamer69",
                "Darthlego",
                "Diamond Nife",
                "djsnj20",
                "DOGMA",
                "DogVTF",
                "drake093104",
                "Entrian",
                "Equinoxux",
                "EternalGrayson",
                "FishBread",
                "goo",
                "Grant Curtiss",
                "haefer.goat.oats",
                "Halleyvetica",
                "Hamsting",
                "help",
                "Iptktp9",
                "J.U.N.E.S",
                "Jace Ufret",
                "Jalapeno9",
                "Jankle",
                "JFL",
                "Kiddorox",
                "Liam Rafle",
                "Magicoal",
                "Mint_loll",
                "MizzUltraViolet DamienTK",
                "Nature",
                "niceguysrage",
                "Nick H",
                "Nightinglade",
                "Nothin Purrsonal",
                "Nova Solarius",
                "NyxxyNightstar",
                "OakhamSam",
                "PantySlack",
                "Patch357",
                "Phil Broome",
                "Qwertz",
                "Reece",
                "roryoftheabyss",
                "RuskieThe3rd",
                "Sable",
                "SakuraWinterz",
                "Salted Warlock",
                "schmoovi",
                "Sharktank6",
                "SirChaos189",
                "SkeletonHunter96",
                "Taelishe",
                "Taylor Olligoci", // also an ex-dev. Listed as "Lilac Olligoci" on Patreon. There were two "Taylor"s on the old list
                "Tethox",
                "That Katsafaros",
                "The Deer Who Sold The World",
                "The Roborex",
                "The Wither",
                "Trinity Series",
                "Tsukara",
                "Vanillin",
                "Vertigo",
                "weisslerren",
                "xAqult",
                "Xtra Trinity 3678",
                "Xtra",
                "Xzier_Tengal",
                "YashimaYamanata",
                "Zachtoplasm",
                "ZoeyPlague",
            ];
            
            // Historical donor list. Please never remove names from here unless you are also adding them to NewPatreonList.
            OriginalPatreonList =
            [
                "_Skeggy_",
                "116taj",
                "26-4-1",
                "2Larry2",
                "3en",
                "3x1t_5tyl3",
                "A_Normal_Person",
                "adain",
                "Adamko",
                "Aden C.N.",
                "Aero",
                "Aero (Aero#4599)",
                "Aeroni", // previously "Toxin"
                "Æthereal",
                "Afzofa",
                "Aidan",
                "Akkolite",
                "Albino gonkvader",
                "Alec",
                "Aleksanders",
                "Aleksh",
                "Alex",
                "Alex N",
                "Alexander",
                "Alexis",
                "Alfragiste",
                "Allegro",
                "allosar",
                "Ally2Cute",
                "Altzeus",
                "anglerraptor",
                "Anish",
                "Anton",
                "Antonie",
                "anything5000",
                "Apotheosis",
                "apotofkoolaid",
                "Arcadia",
                "Arche",
                "Archie",
                "Ari",
                "Ariscottle",
                "Arkhine",
                "Arthur",
                "Arti",
                "asdf935",
                "Ash",
                "Ashamper",
                "Asheel",
                "Ashton",
                "Ashton",
                "Avery",
                "Azura",
                "Azure",
                "Azzilan",
                "BakaQing",
                "Barbara",
                "Ben",
                // "Ben Shapiro", // 01JUN2025: Ozzatron: we already have this as a guide name. That's enough. Melting him in lava is appropriate. Crediting him for funding is not.
                "Bendy",
                "Beta165",
                "bikmin",
                "Bill",
                "Billy",
                "Blackbluue",
                "Bladesaber",
                "Blobby6799",
                "BobIsNotMyRealName",
                "Boomdiada",
                "Borb9834",
                "Bossy Punch",
                "Braden",
                "BreachNClear747",
                "Bread",
                "Brendan",
                "Brian",
                "Brian",
                "Briny_Coffee",
                "Broken Faucet",
                "Bruggs",
                "Bruh.PNG",
                "Brutus",
                "Brutzli",
                "BumbleDoge",
                "Buppercups - Roblox",
                "CaineSenpai",
                "Calcium Comrade",
                "callisto",
                "Cameron",
                "Cameron",
                "Carboniferous",
                "CasualNoLifer",
                "Cerberus",
                "Chaos",
                "ChAoS DiScOrD",
                "ChaosChaos",
                "Chaotic Reks",
                "Chaozhi",
                "Charles",
                "Check pins",
                "Cheddar",
                "Chigbungus",
                "Chip",
                "Chow Chow",
                "ChrigTopher",
                "Christopher",
                "Circuit-Jay",
                "cocodezi_",
                "Cody",
                "Cole",
                "Colin",
                "Colin V",
                "Commander Frostbite",
                "Conner",
                "Coolguystorm YT",
                "Corn M. Cobb",
                "cosmickalamity",
                "CosmicStarIight",
                "CrabBar", // Current dev.
                "Creamy",
                "CrimsonCrips",
                "Crippling-Ambition",
                "Cristian(Mihaii)",
                "Crysthamyr",
                "Culex",
                "Curtis",
                "cytokat",
                "Daawnz",
                "Dakota",
                "Dakota C",
                "DanYami",
                "DaPyRo",
                "darkhawke",
                "Darkus",
                "Darkweb",
                "Darren", // Current dev.
                "Darthlego",
                "Dasdruid",
                "dawn thunder",
                "dawnboi",
                "Dayne",
                "ddoogg88 tdog",
                "Deallly",
                "Dee",
                "DeLordeyeee",
                "DemoN K!ng",
                "dennis",
                "Depressed Dad Gaming",
                "Derdjin",
                "DESPACITO",
                "Destiny Stallcup",
                "Destructoid",
                "DevAesthetic",
                "DevilSunrise",
                "Devin",
                "Devon",
                "Devonte",
                "dexxer65",
                "Dionysos",
                "discokittie",
                "DjackV",
                "djsnj20",
                "Domrinth",
                "Done",
                "Doodled_lynx",
                "Doug",
                "Doveda",
                "Dr. Pawsworth",
                "Drakkece",
                "drenmus!",
                "Drip Veezy",
                "Driser",
                "Duck Satan",
                "Dull",
                "dummyAzure",
                "Dylan",
                "Eddie Spaghetti",
                "EdelVollMilch",
                "edm vibes",
                "Ein",
                "Eisaya",
                "Ekun",
                "Elementari",
                "Elfinlocks",
                "Elijah",
                "Empress Vega",
                "Eragon3942",
                "Eric",
                "Eternal Silence",
                "ethan",
                "Ethan",
                "everquartz",
                "F00d Demon",
                "Face",
                "FaeLoPondering",
                "False",
                "Fartein",
                "Faye",
                "Feels Fishy",
                "Ferret4T",
                "Finnrua",
                "fire",
                "Fish Repairs",
                "FishBread",
                "Fizzlpoprock",
                "Florian",
                "Forge",
                "Freakish",
                "Frederik",
                "Fweepachino",
                "Gameology",
                "GameRDheAsianSandwich",
                "Gamma Freya",
                "garfu",
                "GentSkeleton",
                "Georgios",
                "Gibb50",
                "GIGA MAN",
                "Gilded Gryphon",
                "Glaid",
                "gluten tag",
                "Goblin",
                "Goober",
                "Goomfrontlut",
                "GP",
                "GreenBerry",
                "GreenTea",
                "GregTheSpinarak",
                "Gretchen",
                "Griffin",
                "Grylken",
                "GTW High Cube",
                "Guwahavel",
                "Habb",
                "Hana",
                "Handburger",
                "Hannes",
                "Hans Volter",
                "happy thoughts",
                "Hargestar",
                "Hayden",
                "Hayden",
                "Helixas",
                "HellGoat2",
                "High Charity",
                "Him",
                "Himakaze",
                "Hokojin",
                "Homunculus Derelictus",
                "hoosfire",
                "hubert thieblot",
                "Hunter",
                "Iconic Parker Gaming",
                "Iguy",
                "Indeciiissive",
                "IsaacInsomnia",
                "Izuna",
                "J.U.N.E.S",
                "Jack",
                "JackShizz",
                "Jackson",
                "Jakob",
                "Jalapeno9",
                "James",
                "James",
                "Jankle",
                "Jarod",
                "Javyz",
                "Jaydon",
                "Jaykob",
                "jc.",
                "Jeff",
                "Jeff",
                "Jenonen",
                "JensB__",
                "Jersey",
                "jes",
                "Jessire",
                "Jetpat3",
                "Jheybyrd",
                "jjth0m3",
                "Joe",
                "Joep",
                "Jordan",
                "Jose",
                "Joshua",
                "julius",
                "Just a random guy",
                "just akkolite",
                "JustLonelyPi",
                "Kaden",
                "Kaimonick",
                "Kaledoulas",
                "KAT-G307",
                "Katherine",
                "Kazurgundu",
                "KeL",
                "Kevin",
                "Kevin",
                "kgh8090",
                "Kinzoku",
                "Kipluck",
                "Kiyotu",
                "KJ",
                "Konorango",
                "Korb Orb",
                "Krankwagon",
                "KugelBlitz",
                "KurlozClown",
                "Lacuna",
                "Lady Shira",
                "Lagohz",
                "Lance",
                "Landon",
                "Larry That Barry",
                "Lauren",
                "Leonidas",
                "Levi", // Ex-developer.
                "Levi",
                "Lightedflare",
                "Lilith",
                "Lime-Wars l 1",
                "Littlepiggy",
                "Lodude",
                "LompL",
                "Lord_Lucerne",
                "Loser",
                "Lucas",
                "Lucas",
                "LucasHM",
                "LucasTwocas",
                "Lucazii",
                "Luis",
                "Luke",
                "LumiEvi",
                "LvL-94",
                "M001NG",
                "Madd Cat",
                "Magic Love",
                "Magicoal",
                "MajinBagel",
                "Malik",
                "Marco",
                "Marissa443",
                "Mark",
                "Markie",
                "Marko",
                "Mars",
                "martyrdomination",
                "Maskedmilo",
                "Mathuantie",
                "Matias",
                "Matthew",
                "Max Kim",
                "MaxingOut",
                "Mayhem",
                "MeanieG",
                "Medi",
                "Melvin",
                "Mendzey",
                "Meow",
                "Merubel",
                "Met Vox",
                "Mikabul",
                "Min",
                "MingWhy",
                "Minty Candy",
                "MishiroUsui",
                "Misinput",
                "MissMudflaps",
                "Mister Winchester",
                "MittoMan",
                "MiyoshiEira",
                "Mobian",
                "Mohammad",
                "Moist Lad",
                "Monic",
                "Monti",
                "Moonicento",
                "MovingTarget_086",
                "Mr. Bones",
                "Mr.Matter",
                "MrCreamen",
                "MrNobody",
                "n0tacat",
                "Naglfar",
                "Nanaki",
                "Natalie",
                "Nathan",
                "Navigator",
                "Ne'er Dowell",
                "NEBULA",
                "NebulaMagePlays",
                "Nemesis 041",
                "Neoplasmatic",
                "NepNep",
                "Nexus",
                "Nicholas",
                "Nightskyflyer",
                "Nitronium Productions",
                "Noah",
                "NoOneElse",
                "Nuclear Chaos",
                "Nuclei",
                "Number1piratepan",
                "NuT NiTe",
                "NyanLegacy215",
                "Nyapano",
                "Nycro",
                "Oblivionisbruh",
                "Obsoleek",
                "Oceanman232",
                "OctolingGrimm",
                "oli saer",
                "Olkothan",
                "OnTheAirPogs",
                "oracle",
                "OriginForme487",
                "OrrangProto",
                "Orudeon",
                "Pacnysam",
                "Paltham",
                "Patrera",
                "Patrick",
                "Pedro",
                "Perditio Astrum",
                "Picasso's Bean",
                "Pigeon",
                "Plant Waifu",
                "Pneuma",
                "Pomelo",
                "pomp neigh",
                "Ponynator",
                "Poopifier Poopifly",
                "Popsickle Yoshi",
                "porglesupreme",
                "Potato - Stego",
                "Potion Man",
                "Preston",
                "Primpy",
                "Prism",
                "Professor Pissington",
                "ProfessorWinston",
                "Proffesor prostate",
                "profoundmango69",
                "PsychoGrizzly",
                "Pusheen_",
                "pyobbo",
                "Pyromaniac146",
                "Qelrin",
                "Rando Calrissian",
                "Random Weeb",
                "rawpie2",
                "Real mystlc",
                "Reanamet",
                "Reiter splash",
                "RetroRed",
                "Rinja",
                "Rixu",
                "RKMoon",
                "Robert",
                "RockRecker39",
                "Rolandark",
                "Rooki",
                "Rossadon",
                "Rottingwood",
                "Roxas",
                "Ruben",
                "RuskieThe3rd",
                "Ruthoranium",
                "Ryaegos",
                "Ryan",
                "Ryan",
                "Ryan Baker-Ortiz",
                "Sabrina",
                "Sadouken",
                "Sailor Jolt",
                "Saladify",
                "Samuel",
                "Sanctuary",
                "Sandblast",
                "Sarcosuchus",
                "Schlarfblrfsch",
                "SCONICBOOM",
                "Scribbles",
                "Scrumlet",
                "Seanツ",
                "Sevenfold", // previously "Woah"
                "Shadoku",
                "SharZz",
                "Shaun",
                "Shay", // There were two "Shay"s on the old list
                "sherk",
                "Shifter",
                "Shiny",
                "Shiro",
                "Shirosity", // used to be GlitchOut
                "ShotgunAngel",
                "Shpee",
                "Sigil",
                "sk",
                "Skeli_G",
                "Slim",
                "Smart2004",
                "Smug",
                "Snowy",
                "Soko",
                "Solaire",
                "SoloMael",
                "SolsticeUnlimitd",
                "SomeRando",
                "SoyScoutSmasher",
                "Spider region",
                "Spirit Shield",
                "Splotchycrib",
                "SpookyNinja",
                "Squishy",
                "srxe",
                "Starmitzy",
                "StarryFox",
                "Steven",
                "Stormone",
                "Streakist",
                "Suicide Dreams",
                "Superbeepig",
                "sweatingdishes",
                "T E R M I N A T O R",
                "Tails the Fox 92",
                "Taitou1",
                "Takeru",
                "Talmadge",
                "Taylor",
                "Team",
                "TemperedAether",
                "Terrarian Dragon",
                "Tervastator",
                "Tezguin",
                "That Katsafaros",
                "The Buildmonger",
                "The Davester",
                "The Evolution", // previously "Nathaniel"
                "The Goliath",
                "The Illustrious Sqouinchuousor",
                "The Infinity",
                "The Pyro",
                "The Roborex",
                "The Wolf Commando",
                "thebettercat",
                "TheBlackHand",
                "TheGreatSako",
                "theHoopty",
                "TheSilverGhost",
                "Thomas",
                "Thomas",
                "ThomasThePencil",
                "Thys",
                "Timon",
                "TitaniumLlama",
                "Tomat (Stevie)",
                "Tombarry Expresserino",
                "topnormal",
                "Trinity Series",
                "TwanTheGOAT",
                "Tweee",
                "Tyler",
                "Tyler",
                "Uberransy",
                "Ulmod",
                "Ultra Succ",
                "Umberto",
                "Underlost",
                "Valkyrie",
                "vcf55",
                "Veine",
                "velneu",
                "VeryMasterNinja",
                "Vetus",
                "Victor",
                "Vimek Xol",
                "Vmar98",
                "Vorbis",
                "Vroomy Has -3,000 IQ",
                "Vyster", // previously "Bewearium"
                "Warlok",
                "Whale",
                "Whitegiraffe",
                "Will",
                "william",
                "William",
                "William",
                "WillyDilly",
                "WinterTire",
                "Wodernet",
                "Wolfmaw",
                "WrathOfOlympus",
                "Xaphlactus",
                "xAqult",
                "xd Ow0",
                "XDkilljoy65XX",
                "xElectrix_",
                "Xenocrona",
                "Xenocrona",
                "Xsiana",
                "XusTingo9",
                "Yatagarasu",
                "yayoi",
                "Yhashtur",
                "yiumik",
                "YuH", // Current dev.
                "YumeiSenshi",
                "Yumi",
                "Zacky",
                "Zekai",
                "Zerafir",
                "Zerimore",
                "zombie wolf",
                "Zombieh",
                "zombieseatflesh7",
                "Zombified _G",
                "ZyferDex_",
                "병현 송",
            ];

            // Staple the two lists together.
            List = [..OriginalPatreonList, ..NewPatreonList];
        }

        public override void Unload()
        {
            OriginalPatreonList = null;
            NewPatreonList = null;
            List = null;
        }
    }
}
