using System.Collections.Generic;
using System.Linq;
using Terraria;
using Terraria.ModLoader;

namespace CalamityMod.Systems.Collections
{
    /// <summary>
    /// A <see cref="ModSystem"/> that stores all of Calamity's Patreon donator's usernames.
    /// </summary>
    public sealed class DonatorsNameList : ModSystem
    {
        public static IList<string> List { get; private set; }

        /// <summary>
        /// This list contains all the donors of the current Patreon, which is for the entire Calamity Dev Team. <br /><br />
        /// <b>There is no overlap between OriginalPatreonList and this list.</b><br /><br />
        /// Any user who donates to the new team-wide Patreon gets added to this new list and removed from the old one.
        /// </summary>
        internal static IList<string> NewPatreonList { get; private set; }

        /// <summary>
        /// This list contains all the donors of the previous Patreon, which was in Fabsol's name. <br /><br />
        /// <b>There is no overlap between NewPatreonList and this list.</b><br /><br />
        /// Any user who donates to the new team-wide Patreon gets added to the new list and removed from this one. 
        /// </summary>
        internal static IList<string> OriginalPatreonList { get; private set; }

        public override void OnModLoad()
        {
            // All donors at the $10 - Brimstone tier or higher are included in the shout-out.
            // This is updated for each release.
            NewPatreonList =
            [
                "Aerosyn",
                "Arcxus",
                "awesomechapro",
                "azazel",
                "BlueRay_256",
                "botbot94",
                "Chin",
                "Cinder",
                "drake093104",
                "Grant Curtiss",
                "Jace Ufret",
                "JFL",
                "MizzUltraViolet",
                "Nature",
                "Nick H",
                "Nightinglade",
                "Patch357",
                "Phil Broome",
                "roryoftheabyss",
                "Sable",
                "SakuraWinterz",
                "Salted Warlock",
                "Shayy", // Current dev. Listed as "Shay" on Patreon.
                "SirChaos189",
                "SkeletonHunter96",
                "Taylor Olligoci", // also an ex-dev. Listed as "Lilac Olligoci" on Patreon. There were two "Taylor"s on the old list
                "Xtra Trinity 3678",
                "Zachtoplasm",
                "ZoeyPlague",
            ];
            
            // Historical donor list. Please never remove names from here unless you are also adding them to NewPatreonList.
            OriginalPatreonList =
            [
                "2Larry2",
                "3x1t_5tyl3",
                "Æthereal",
                "Aero (Aero#4599)",
                "Afzofa",
                "Alec",
                "Aleksanders",
                "Aleksh",
                "Alexander",
                "Apotheosis",
                "Arche",
                "Ari",
                "Arkhine",
                "Arti",
                "asdf935",
                "Azura",
                "BakaQing",
                "Ben",
                // "Ben Shapiro", // 0JUN2025: Ozzatron: we already have this as a guide name. That's enough. Melting him in lava is appropriate. Crediting him for funding is not.
                "Bendy",
                "Beta165",
                "Bladesaber",
                "BobIsNotMyRealName",
                "Boomdiada",
                "Braden",
                "Bread",
                "Brendan",
                "Broken Faucet",
                "BumbleDoge",
                "Cameron",
                "Cerberus",
                "Chaos",
                "Chaotic Reks",
                "Check pins",
                "Chigbungus",
                "Chip",
                "Christopher",
                "Circuit-Jay",
                "cocodezi_",
                "Commmander Frostbite",
                "cosmickalamity",
                "CrabBar", // Current dev.
                "CrimsonCrips",
                "Crysthamyr",
                "Culex",
                "cytokat",
                "Daawnz",
                "Dakota",
                "DanYami",
                "DaPyRo",
                "Darren", // Current dev.
                "Dasdruid",
                "dawn thunder",
                "Dee",
                "DemoN K!ng",
                "Depressed Dad Gaming",
                "DevAesthetic",
                "DevilSunrise",
                "Devon",
                "Devonte",
                "djsnj20",
                "Doveda",
                "Drakkece",
                "Drip Veezy",
                "Ein",
                "Eisaya",
                "Elfinlocks",
                "Eragon3942",
                "Eternal Silence",
                "F00d Demon",
                "False",
                "Faye",
                "Fish Repairs",
                "Fizzlpoprock",
                "Florian",
                "Frederik",
                "GameRDheAsianSandwich",
                "GentSkeleton",
                "Gibb50",
                "Glaid",
                "Guwahavel",
                "Hannes",
                "Hans Volter",
                "Helixas",
                "High Charity",
                "hubert thieblot",
                "Izuna",
                "Jack",
                "JackShizz",
                "Jarod",
                "Javyz",
                "Jeff",
                "Jenonen",
                "Joshua",
                "Just a random guy",
                "KAT-G307",
                "Krankwagon",
                "Levi", // Ex-developer.
                "Lilith",
                "Littlepiggy",
                "Lodude",
                "Lagohz",
                "LompL",
                "Lucazii",
                "Luis",
                "MajinBagel",
                "Malik",
                "Marissa443",
                "Melvin",
                "Mendzey",
                "Min",
                "MingWhy",
                "Minty Candy",
                "MishiroUsui",
                "Mister Winchester",
                "Mobian",
                "Moist Lad",
                "MovingTarget_086",
                "Naglfar",
                "Nanaki",
                "NebulaMagePlays",
                "Neoplasmatic",
                "NepNep",
                "Olkothan",
                "Orudeon",
                "Pedro",
                "Pigeon",
                "Preston",
                "Primpy",
                "Prism",
                "profoundmango69",
                "pyobbo",
                "Rando Calrissian",
                "Random Weeb",
                "Rinja",
                "RKMoon",
                "Rossadon",
                "Ruthoranium",
                "Ryan Baker-Ortiz",
                "Samuel",
                "Sandblast",
                "Sarcosuchus",
                "Shay", // There were two "Shay"s on the old list
                "Shifter",
                "Shiro",
                "Shirosity", // used to be GlitchOut
                "ShotgunAngel",
                "Snowy",
                "SoloMael",
                "SpookyNinja",
                "Stormone",
                "Streakist",
                "Tails the Fox 92",
                "Takeru",
                "Taylor",
                "Tervastator",
                "The Buildmonger",
                "The Goliath",
                "The Illustrious Sqouinchuousor",
                "TheBlackHand",
                "TheSilverGhost",
                "ThomasThePencil",
                "Thys",
                "Timon",
                "Tombarry Expresserino",
                "TwanTheGOAT",
                "Veine",
                "Vetus",
                "Victor",
                "Vmar98",
                "Vroomy Has -3,000 IQ",
                "Vorbis",
                "Warlok",
                "Whitegiraffe",
                "Will",
                "william",
                "William",
                "Wodernet",
                "Xaphlactus",
                "xd Ow0",
                "Yatagarasu",
                "YuH", // Current dev.
                "Zacky",
                "Zombieh",

                "Brutzli",
                "Yhashtur",
                "Zekai",
                "Doug",
                "Uberransy",
                "KurlozClown",
                "Nemesis 041",
                "Asheel",
                "Hayden",
                "Lightedflare",
                "Lady Shira",
                "Devin",
                "Qelrin",
                "Thomas",
                "Ne'er Dowell",
                "Potion Man",
                "martyrdomination",
                "Destructoid",
                "Coolguystorm YT",
                "Wolfmaw",
                "yiumik",
                "Destiny Stallcup",
                "GreenBerry",
                "SolsticeUnlimitd",
                "darkhawke",
                "oracle",
                "YumeiSenshi",
                "Cameron",
                "Aeroni", // previously "Toxin"
                "Fweepachino",
                "DESPACITO",
                "Altzeus",
                "Ryan",
                "Spider region",
                "WinterTire",
                "Nycro",
                "Vyster", // previously "Bewearium"
                "William",
                "HellGoat2",
                "116taj",
                "CaineSenpai",
                "Suicide Dreams",
                "Roxas",
                "Obsoleek",
                "Jetpat3",
                "GreenTea",
                "Woah",
                "Ryaegos",
                "Popsickle Yoshi",
                "Arcadia",
                "JensB__",
                "Nuclei",
                "Picasso's Bean",
                "Corn M. Cobb",
                "kgh8090",
                "Luke",
                "Barbara",
                "Alexis",
                "Soko",
                "Albino gonkvader",
                "Monic",
                "Slim",
                "ChaosChaos",
                "Deallly",
                "Jeff",
                "vcf55",
                "Kazurgundu",
                "Jheybyrd",
                "Kipluck",
                "SCONICBOOM",
                "Mr.Matter",
                "Billy",
                "jjth0m3",
                "GTW High Cube",
                "Sabrina",
                "Potato - Stego",
                "Perditio Astrum",
                "MaxingOut",
                "SharZz",
                "Allegro",
                "hoosfire",
                "Lauren",
                "Ultra Succ",
                "Ethan",
                "Pacnysam",
                "dummyAzure",
                "Jaykob",
                "Goblin",
                "NoOneElse",
                "Nicholas",
                "oli saer",
                "Blobby6799",
                "Domrinth",
                "zombieseatflesh7",
                "Shiny",
                "Whale",
                "The Infinity",
                "MrCreamen",
                "TemperedAether",
                "LucasTwocas",
                "JustLonelyPi",
                "Brian",
                "Ashton",
                "Rolandark",
                "Ally2Cute",
                "Dionysos",
                "Plant Waifu",
                "fire",
                "Charles",
                "Kaden",
                "Dr. Pawsworth",
                "Jackson",
                "Freakish",
                "Ashamper",
                "Kinzoku",
                "Elementari",
                "The Wolf Commando",
                "Jordan",
                "Jessire",
                "Ashton",
                "callisto",
                "velneu",
                "Mathuantie",
                "Robert",
                "Matias",
                "T E R M I N A T O R",
                "apotofkoolaid",
                "Matthew",
                "Terrarian Dragon",
                "Pomelo",
                "Thomas",
                "Iconic Parker Gaming",
                "Jaydon",
                "Aidan",
                "Avery",
                "yayoi",
                "Splotchycrib",
                "GIGA MAN",
                "Eric",
                "Merubel",
                "Smug",
                "Lime-Wars l 1",
                "WillyDilly",
                "xAqult",
                "Himakaze",
                "Face",
                "Carboniferous",
                "James",
                "Taitou1",
                "Yumi",
                "NEBULA",
                "Blackbluue",
                "Alex",
                "Ruben",
                "Rixu",
                "Antonie",
                "Zerimore",
                "Oblivionisbruh",
                "Loser",
                "Patrick",
                "Magic Love",
                "gluten tag",
                "RetroRed",
                "Katherine",
                "SoyScoutSmasher",
                "Jersey",
                "Reiter splash",
                "Conner",
                "Ekun",
                "Driser",
                "bikmin",
                "MittoMan",
                "Pyromaniac146",
                "Eddie Spaghetti",
                "Colin",
                "ZyferDex_",
                "LumiEvi",
                "Anish",
                "MissMudflaps",
                "Valkyrie",
                "anglerraptor",
                "Scribbles",
                "Pneuma",
                "OrrangProto",
                "Tomat (Stevie)",
                "That Katsafaros",
                "PsychoGrizzly",
                "Dayne",
                "Hargestar",
                "The Pyro",
                "Lucas",
                "Superbeepig",
                "Larry That Barry",
                "Monti",
                "StarryFox",
                "Kevin",
                "Poopifier Poopifly",
                "Lacuna",
                "Nathan",
                "Handburger",
                "XusTingo9",
                "Underlost",
                "julius",
                "Mark",
                "Habb",
                "Reanamet",
                "Empress Vega",
                "Team",
                "GP",
                "Xsiana",
                "NyanLegacy215",
                "ethan",
                "Trinity Series",
                "M001NG",
                "WrathOfOlympus",
                "dennis",
                "Darkweb",
                "Chaozhi",
                "Mars",
                "Elijah",
                "Tezguin",
                "Shpee",
                "Archie",
                "Meow",
                "CosmicStarIight",
                "Alfragiste",
                "Number1piratepan",
                "Noah",
                "Max Kim",
                "Anton",
                "edm vibes",
                "Hunter",
                "Doodled_lynx",
                "3en",
                "Kiyotu",
                "Aero",
                "Iguy",
                "병현 송",
                "Tyler",
                "Leonidas",
                "GregTheSpinarak",
                "Cheddar",
                "Alex N",
                "Magicoal",
                "Seanツ",
                "Ariscottle",
                "Kevin",
                "OnTheAirPogs",
                "Zerafir",
                "Bill",
                "Starmitzy",
                "FaeLoPondering",
                "Brian",
                "Smart2004",
                "sherk",
                "Squishy",
                "Ash",
                "rawpie2",
                "Hokojin",
                "sk",
                "Done",
                "MeanieG",
                "Sanctuary",
                "Landon",
                "Moonicento",
                "Hayden",
                "Steven",
                "Hana",
                "Mikabul",
                "Nathaniel",
                "Brutus",
                "EdelVollMilch",
                "garfu",
                "NuT NiTe",
                "adain",
                "Dylan",
                "Lucas",
                "Arthur",
                "sweatingdishes",
                "pomp neigh",
                "Proffesor prostate",
                "Saladify",
                "26-4-1",
                "VeryMasterNinja",
                "Vorbis",
                "Nyapano",
                "Shadoku",
                "allosar",
                "jes",
                "Paltham",
                "Fartein",
                "Derdjin",
                "A_Normal_Person",
                "Duck Satan",
                "Jalapeno9",
                "Grylken",
                "Nexus",
                "KJ",
                "Goober",
                "ChAoS DiScOrD",
                "Mayhem",
                "Zombified _G",
                "Madd Cat",
                "Natalie",
                "Solaire",
                "Dakota C",
                "The Davester",
                "Jose",
                "Him",
                "Umberto",
                "Lance",
                "Navigator",
                "Ferret4T",
                "Rooki",
                "LvL-94",
                "Feels Fishy",
                "Korb Orb",
                "Calcium Comrade",
                "Talmadge",
                "ddoogg88 tdog",
                "CasualNoLifer",
                "Bossy Punch",
                "Creamy",
                "Tyler",
                "topnormal",
                "Gilded Gryphon",
                "Nightskyflyer",
                "Schlarfblrfsch",
                "MrNobody",
                "Aden C.N.",
                "zombie wolf",
                "n0tacat",
                "Marko",
                "dexxer65",
                "DeLordeyeee",
                "Kaledoulas",
                "Mohammad",
                "Skeli_G",
                "Sigil",
                "Dull",
                "DjackV",
                "Misinput",
                "Gameology",
                "KugelBlitz",
                "TheGreatSako",
                "Joep",
                "Rottingwood",
                "anything5000",
                "Gretchen",
                "Spirit Shield",
                "Briny_Coffee",
                "_Skeggy_",
                "just akkolite",
                "J.U.N.E.S",
                "Bruggs",
                "Vimek Xol",
                "Oceanman232",
                "Sadouken",
                "srxe",
                "ProfessorWinston",
                "OctolingGrimm",
                "Cole",
                "Markie",
                "Met Vox",
                "Tweee",
                "Kaimonick",
                "Chow Chow",
                "drenmus!",
                "Nitronium Productions",
                "Goomfrontlut",
                "Akkolite",
                "Shaun",
                "Bruh.PNG",
                "James",
                "Lord_Lucerne",
                "Ulmod",
                "Adamko",
                "Gamma Freya",
                "Finnrua",
                "Maskedmilo",
                "RockRecker39",
                "Konorango",
                "Indeciiissive",
                "Curtis",
                "Ponynator",
                "Crippling-Ambition",
                "TitaniumLlama",
                "OriginForme487",
                "FishBread",
                "Real mystlc",
                "Levi",
                "jc.",
                "Medi",
                "Jakob",
                "Borb9834",
                "Georgios",
                "KeL",
                "Cody",
                "Cristian(Mihaii)",
                "Marco",
                "RuskieThe3rd",
                "BreachNClear747",
                "happy thoughts",
                "Azure",
                "theHoopty",
                "porglesupreme",
                "XDkilljoy65XX",
                "Mr. Bones",
                "dawnboi",
                "Joe",
                "Sailor Jolt",
                "SomeRando",
                "Nuclear Chaos",
                "Jankle",
                "The Roborex",
                "everquartz",
                "discokittie",
                "IsaacInsomnia",
                "xElectrix_",
                "Forge",
                "MiyoshiEira",
                "thebettercat",
                "Darthlego",
                "Azzilan",
                "Griffin",
                "LucasHM",
                "ChrigTopher",
                "Colin V",
                "Scrumlet",
                "Darkus",
                "Homunculus Derelictus",
                "Professor Pissington",
                "Buppercups - Roblox",
                "Pusheen_",
                "Patrera"
            ];

            // Staple the two lists together.
            List = [..OriginalPatreonList, ..NewPatreonList];
        }

        public override void Unload()
        {
            OriginalPatreonList = null;
            NewPatreonList = null;
            List = null;
        }
    }
}
