using System.Collections.Generic;
using Terraria;
using Terraria.ModLoader;

namespace CalamityMod.Systems.Collections
{
    /// <summary>
    /// A <see cref="ModSystem"/> that stores all of Calamity's Patreon donator's usernames.
    /// </summary>
    public sealed class DonatorsNameList : ModSystem
    {
        public static IList<string> List { get; private set; }

        public override void OnModLoad()
        {
            List =
            [
                "Vorbis",
                "SoloMael",
                "Chaotic Reks",
                "The Buildmonger",
                "YuH",
                "Littlepiggy",
                "LompL",
                "Lilith",
                "Ben Shapiro",
                "Frederik",
                "Faye",
                "Gibb50",
                "Braden",
                "Hannes",
                "profoundmango69",
                "Jack",
                "Hans Volter",
                "Krankwagon",
                "MishiroUsui",
                "Arkhine",
                "Lodude",
                "DevAesthetic",
                "Mister Winchester",
                "Zacky",
                "Veine",
                "Javyz",
                "Shifter",
                "Crysthamyr",
                "Elfinlocks",
                "Ein",
                "2Larry2",
                "Jenonen",
                "Arti",
                "Tervastator",
                "Luis",
                "Alexander",
                "BakaQing",
                "Taylor",
                "Xaphlactus",
                "MajinBagel",
                "Bendy",
                "Rando Calrissian",
                "Tails the Fox 92",
                "Bread",
                "Minty Candy",
                "Preston",
                "MovingTarget_086",
                "Shiro",
                "Chip",
                "Taylor",
                "ShotgunAngel",
                "Sandblast",
                "ThomasThePencil",
                "Aero (Aero#4599)",
                "Shirosity", // used to be GlitchOut
                "Daawnz",
                "CrabBar",
                "Yatagarasu",
                "Jarod",
                "Zombieh",
                "MingWhy",
                "Random Weeb",
                "Afzofa",
                "Eragon3942",
                "TheBlackHand",
                "william",
                "Samuel",
                "Christopher",
                "DemoN K!ng",
                "Malik",
                "Ryan Baker-Ortiz",
                "Aleksanders",
                "TheSilverGhost",
                "Lucazii",
                "Shay",
                "Prism",
                "BobIsNotMyRealName",
                "Guwahavel",
                "Azura",
                "Joshua",
                "Doveda",
                "William",
                "Arche",
                "DevilSunrise",
                "Yanmei",
                "Chaos",
                "Ryan",
                "Fish Repairs",
                "Melvin",
                "Vroomy Has -3,000 IQ",
                "The Goliath",
                "DaPyRo",
                "Takeru",
                "Circuit-Jay",
                "Commmander Frostbite",
                "cytokat",
                "Cameron",
                "Orudeon",
                "BumbleDoge",
                "Naglfar",
                "Helixas",
                "Vetus",
                "High Charity",
                "Devonte",
                "Cerberus",
                "Brendan",
                "Victor",
                "KAT-G307",
                "Tombarry Expresserino",
                "Drip Veezy",
                "Glaid",
                "Apotheosis",
                "Bladesaber",
                "Devon",
                "Ruthoranium",
                "cocodezi_",
                "Mendzey",
                "GameRDheAsianSandwich",
                "Chigbungus",
                "Streakist",
                "Eisaya",
                "Xenocrona",
                "RKMoon",
                "Eternal Silence",
                "Jeff",
                "Beta165",
                "DanYami",
                "Xenocrona",
                "Ari",
                "cosmickalamity",
                "xd Ow0",
                "Darren",
                "Florian",
                "dawn thunder",
                "asdf935",
                "GentSkeleton",
                "Fizzlpoprock",
                "Pigeon",
                "Aleksh",
                "Just a random guy",
                "Dee",
                "Æthereal",
                "Broken Faucet",
                "Sarcosuchus",
                "Marissa443",
                "Warlok",
                "JackShizz",
                "NebulaMagePlays",
                "Primpy",
                "Thys",
                "Min",
                "Wodernet",
                "Pedro",
                "Depressed Dad Gaming",
                "Snowy",
                "Stormone",
                "Mobian",
                "Rinja",
                "Check pins",
                "Dakota",
                "Neoplasmatic",
                "False",
                "Whitegiraffe",
                "Drakkece",
                "Levi",
                "Izuna",
                "djsnj20",
                "pyobbo",
                "Alec",
                "The Illustrious Sqouinchuousor",
                "Moist Lad",
                "TwanTheGOAT",
                "3x1t_5tyl3",
                "Will",
                "SpookyNinja",
                "Boomdiada",
                "Culex",
                "Rossadon",
                "Ben",
                "hubert thieblot",
                "NepNep",
                "Nanaki",
                "CrimsonCrips",
                "Lagohz",
                "Timon",
                "F00d Demon",
                "Olkothan",
                "Vmar98",
                "Dasdruid",
                "Cinder",
                "Brutzli",
                "Yhashtur",
                "Zekai",
                "Doug",
                "Uberransy",
                "KurlozClown",
                "Nemesis 041",
                "Asheel",
                "Hayden",
                "Lightedflare",
                "Lady Shira",
                "Devin",
                "Qelrin",
                "Thomas",
                "Ne'er Dowell",
                "Potion Man",
                "martyrdomination",
                "Destructoid",
                "Coolguystorm YT",
                "Wolfmaw",
                "yiumik",
                "Destiny Stallcup",
                "GreenBerry",
                "SolsticeUnlimitd",
                "darkhawke",
                "oracle",
                "YumeiSenshi",
                "Cameron",
                "Aeroni", // previously "Toxin"
                "Fweepachino",
                "DESPACITO",
                "Altzeus",
                "Ryan",
                "Spider region",
                "WinterTire",
                "Nycro",
                "Vyster", // previously "Bewearium"
                "William",
                "HellGoat2",
                "116taj",
                "CaineSenpai",
                "Suicide Dreams",
                "Roxas",
                "Obsoleek",
                "Jetpat3",
                "GreenTea",
                "Woah",
                "Ryaegos",
                "Popsickle Yoshi",
                "Arcadia",
                "JensB__",
                "Nuclei",
                "Picasso's Bean",
                "Corn M. Cobb",
                "kgh8090",
                "Luke",
                "Barbara",
                "Alexis",
                "Soko",
                "Albino gonkvader",
                "Monic",
                "Slim",
                "ChaosChaos",
                "Deallly",
                "Jeff",
                "vcf55",
                "Kazurgundu",
                "Jheybyrd",
                "Kipluck",
                "SCONICBOOM",
                "Mr.Matter",
                "Billy",
                "jjth0m3",
                "GTW High Cube",
                "Sabrina",
                "Potato - Stego",
                "Perditio Astrum",
                "MaxingOut",
                "SharZz",
                "Allegro",
                "hoosfire",
                "Lauren",
                "Ultra Succ",
                "Ethan",
                "Pacnysam",
                "dummyAzure",
                "Jaykob",
                "Goblin",
                "NoOneElse",
                "Nicholas",
                "oli saer",
                "Blobby6799",
                "Domrinth",
                "zombieseatflesh7",
                "Shiny",
                "Whale",
                "The Infinity",
                "MrCreamen",
                "TemperedAether",
                "LucasTwocas",
                "JustLonelyPi",
                "Brian",
                "Ashton",
                "Rolandark",
                "Ally2Cute",
                "Dionysos",
                "Plant Waifu",
                "fire",
                "Charles",
                "Kaden",
                "Dr. Pawsworth",
                "Jackson",
                "Freakish",
                "Ashamper",
                "Kinzoku",
                "Elementari",
                "The Wolf Commando",
                "Jordan",
                "Jessire",
                "Ashton",
                "callisto",
                "velneu",
                "Mathuantie",
                "Robert",
                "Matias",
                "T E R M I N A T O R",
                "apotofkoolaid",
                "Matthew",
                "Terrarian Dragon",
                "Pomelo",
                "Thomas",
                "Iconic Parker Gaming",
                "Jaydon",
                "Aidan",
                "Avery",
                "yayoi",
                "Splotchycrib",
                "GIGA MAN",
                "Eric",
                "Merubel",
                "Smug",
                "Lime-Wars l 1",
                "WillyDilly",
                "xAqult",
                "Himakaze",
                "Face",
                "Carboniferous",
                "James",
                "Taitou1",
                "Yumi",
                "NEBULA",
                "Blackbluue",
                "Alex",
                "Ruben",
                "Rixu",
                "Antonie",
                "Zerimore",
                "Oblivionisbruh",
                "Loser",
                "Patrick",
                "Magic Love",
                "gluten tag",
                "RetroRed",
                "Katherine",
                "SoyScoutSmasher",
                "Jersey",
                "Reiter splash",
                "Conner",
                "Ekun",
                "Driser",
                "bikmin",
                "MittoMan",
                "Pyromaniac146",
                "Eddie Spaghetti",
                "Colin",
                "ZyferDex_",
                "LumiEvi",
                "Anish",
                "MissMudflaps",
                "Valkyrie",
                "anglerraptor",
                "Scribbles",
                "Pneuma",
                "OrrangProto",
                "Tomat (Stevie)",
                "That Katsafaros",
                "PsychoGrizzly",
                "Dayne",
                "Hargestar",
                "The Pyro",
                "Lucas",
                "Superbeepig",
                "Larry That Barry",
                "Monti",
                "StarryFox",
                "Kevin",
                "Poopifier Poopifly",
                "Lacuna",
                "Nathan",
                "Handburger",
                "XusTingo9",
                "Underlost",
                "julius",
                "Mark",
                "Habb",
                "Reanamet",
                "Empress Vega",
                "Team",
                "GP",
                "Xsiana",
                "NyanLegacy215",
                "ethan",
                "Trinity Series",
                "M001NG",
                "WrathOfOlympus",
                "dennis",
                "Darkweb",
                "Chaozhi",
                "Mars",
                "Elijah",
                "Tezguin",
                "Shpee",
                "Archie",
                "Meow",
                "CosmicStarIight",
                "Alfragiste",
                "Number1piratepan",
                "Noah",
                "Max Kim",
                "Anton",
                "edm vibes",
                "Hunter",
                "Doodled_lynx",
                "3en",
                "Kiyotu",
                "Aero",
                "Iguy",
                "병현 송",
                "Tyler",
                "Leonidas",
                "GregTheSpinarak",
                "Cheddar",
                "Alex N",
                "Magicoal",
                "Seanツ",
                "Ariscottle",
                "Kevin",
                "OnTheAirPogs",
                "Zerafir",
                "Bill",
                "Starmitzy",
                "FaeLoPondering",
                "Brian",
                "Smart2004",
                "sherk",
                "Squishy",
                "Ash",
                "rawpie2",
                "Hokojin",
                "sk",
                "Done",
                "MeanieG",
                "Sanctuary",
                "Landon",
                "Moonicento",
                "Hayden",
                "Steven",
                "Hana",
                "Mikabul",
                "Nathaniel",
                "Brutus",
                "EdelVollMilch",
                "garfu",
                "NuT NiTe",
                "adain",
                "Dylan",
                "Lucas",
                "Arthur",
                "sweatingdishes",
                "pomp neigh",
                "Proffesor prostate",
                "Saladify",
                "26-4-1",
                "VeryMasterNinja",
                "Vorbis",
                "Nyapano",
                "Shadoku",
                "allosar",
                "jes",
                "Paltham",
                "Fartein",
                "Derdjin",
                "A_Normal_Person",
                "Duck Satan",
                "Jalapeno9",
                "Grylken",
                "Nexus",
                "KJ",
                "Goober",
                "ChAoS DiScOrD",
                "Mayhem",
                "Zombified _G",
                "Madd Cat",
                "Natalie",
                "Solaire",
                "Dakota C",
                "The Davester",
                "Jose",
                "Him",
                "Umberto",
                "Lance",
                "Navigator",
                "Ferret4T",
                "Rooki",
                "LvL-94",
                "Feels Fishy",
                "Korb Orb",
                "Calcium Comrade",
                "Talmadge",
                "ddoogg88 tdog",
                "CasualNoLifer",
                "Bossy Punch",
                "Creamy",
                "Tyler",
                "topnormal",
                "Gilded Gryphon",
                "Nightskyflyer",
                "Schlarfblrfsch",
                "MrNobody",
                "Aden C.N.",
                "zombie wolf",
                "n0tacat",
                "Marko",
                "dexxer65",
                "DeLordeyeee",
                "Kaledoulas",
                "Mohammad",
                "Skeli_G",
                "Arcxus",
                "Sigil",
                "Dull",
                "DjackV",
                "Misinput",
                "Gameology",
                "KugelBlitz",
                "TheGreatSako",
                "Joep",
                "Rottingwood",
                "anything5000",
                "Gretchen",
                "Spirit Shield",
                "Briny_Coffee",
                "_Skeggy_",
                "just akkolite",
                "J.U.N.E.S",
                "Bruggs",
                "Vimek Xol",
                "Oceanman232",
                "Sadouken",
                "srxe",
                "ProfessorWinston",
                "OctolingGrimm",
                "Cole",
                "Markie",
                "Met Vox",
                "Tweee",
                "Kaimonick",
                "Chow Chow",
                "drenmus!",
                "Nitronium Productions",
                "Goomfrontlut",
                "Akkolite",
                "Shaun",
                "Bruh.PNG",
                "James",
                "Lord_Lucerne",
                "Ulmod",
                "Adamko",
                "Gamma Freya",
                "Finnrua",
                "Maskedmilo",
                "RockRecker39",
                "Konorango",
                "Indeciiissive",
                "Curtis",
                "Ponynator",
                "Crippling-Ambition",
                "TitaniumLlama",
                "OriginForme487",
                "FishBread",
                "Real mystlc",
                "Levi",
                "jc.",
                "Medi",
                "Jakob",
                "Borb9834",
                "Georgios",
                "KeL",
                "Cody",
                "Cristian(Mihaii)",
                "Marco",
                "RuskieThe3rd",
                "BreachNClear747",
                "happy thoughts",
                "Azure",
                "theHoopty",
                "porglesupreme",
                "XDkilljoy65XX",
                "Mr. Bones",
                "dawnboi",
                "Joe",
                "Sailor Jolt",
                "SomeRando",
                "Nuclear Chaos",
                "Jankle",
                "The Roborex",
                "everquartz",
                "discokittie",
                "IsaacInsomnia",
                "xElectrix_",
                "Forge",
                "MiyoshiEira",
                "thebettercat",
                "Darthlego",
                "Azzilan",
                "Griffin",
                "LucasHM",
                "ChrigTopher",
                "Colin V",
                "Scrumlet",
                "Darkus",
                "Homunculus Derelictus",
                "Professor Pissington",
                "Buppercups - Roblox",
                "Pusheen_",
                "Patrera"
            ];
        }

        public override void Unload() => List = null;

        /// <summary>
        /// Returns 25 random donator usernames.
        /// </summary>
        public static string[] GetRandomDonors()
        {
            List<string> donorList = new(List);
            const int maxDonorsListed = 25;
            string[] donors = new string[maxDonorsListed];
            for (int i = 0; i < maxDonorsListed; i++)
            {
                donors[i] = donorList[Main.rand.Next(donorList.Count)];
                donorList.Remove(donors[i]);
            }

            return donors;
        }
    }
}
